---
version: 0.2

phases:
  install:
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - yarn install --pure-lockfile
  build:
    commands:
      - yarn build

artifacts:
  files:
    - '**/*'
  base-directory: build/public
...
