Service: usurper

PreDeploy: preDeploy.py
PostDeploy: postDeploy.py

Stacks:
  Global:
    Tags:
      Name: $SERVICE-$STAGE
      Owner: wse
      Contact: web-and-software-engineering-group@nd.edu
  Single:
    - Name: $SERVICE-$STAGE
      Template: webTemplate.yml
      Tags:
        Description: $SERVICE Website Stack
      Parameters:
        AcmCertificateArn: ${CERT_ARN}
        FQDN: ${FQDN}
        TemplateBucket: $DEPLOY_BUCKET
        TemplateFolder: $DEPLOY_FOLDER

Artifacts:
  Templates:
    - webTemplate.yml
  Zips:
    -
      Name: backup
      Files:
        - ../backup/index.js
        - ../backup/node_modules
